config/routes.rb
Rails.application.routes.draw do
  get 'session_google/create'

  get 'session_google/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
    devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  #WEB ROUTES
  get '200.162.7.62.nip.io:3000/auth/:provider/callback', to: 'session_google#create'
  get '200.162.7.62.nip.io:3000/auth/failure', to: redirect('/')
  get '200.162.7.62.nip.io:3000/signout', to: 'session_google#destroy', as: 'signout'

  get '/dashboard/index', to: 'dashboard#index', as: 'dash'

  resources :session_google, only: [:create, :destroy]
  
  resources :roles do
    put 'toggle_status', on: :member
  end
  resources :laboratories do
    put 'toggle_status', on: :member
  end
  resources :clients do
    put 'toggle_status', on: :member
  end
  resources :employees do
    put 'toggle_status', on: :member
  end
  resources :inventories do
    put 'toggle_status', on: :member
  end
  resources :supplies do
    put 'toggle_status', on: :member
  end  
  resources :sample_methods do
    put 'toggle_status', on: :member
  end
  resources :classified_services do
    get 'work_check', on: :member
    put 'work_check_update', on: :member
  end
  resources :services do
    get 'search', on: :collection
    get 'work_check', on: :member
    put 'work_check_update', on: :member
    get 'service_end', on: :member
    put 'service_end_update', on: :member
  end
  
  resources :users
  resources :contracts
  resources :sample_methods
  resources :quotations do
    post 'get_sample_methods', on: :collection
    post 'get_sample_method', on: :collection
  end
  resources :requests
  resources :results
  resources :work_orders
  resources :logs
  resources :service_quotations
  resources :services
  resources :sample_categories do
    put 'toggle_status', on: :member
  end
  resources :check_services do
    get 'search', on: :collection
  end
  resources :classified_services
  resources :work_classified_services do 
    get 'values', on: :member
  end
  resources :historic_custodies 
  resources :system_parameters
  resources :contact_us
  resources :audits

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

  before_action :set_employee, only: [:show, :edit, :update, :toggle_status, :destroy]
  before_action :roles, only: [:new, :create, :update, :edit]
  before_action :laboratories, only: [:new, :create, :update, :edit]

  def index
    @employees = User.own_per_user(current_user).employee
  end

  def show
  end

  def new
    @employee = User.new
  end  

  def edit
  end

  def create
    @employee = User.new employee_params
    @employee.set_laboratory(current_user)  unless current_user.admin?
    if (@employee.set_password).save
      @employee.employee!
      current_user.register_audit "Creacion de trabajador", "added", @employee.id, @employee.full_name, @employee.class.to_s
      redirect_to employees_path        
    else
      render :new        
    end
  end

  def update    
    if @employee.update employee_params.except(:password)
      current_user.register_audit "Actualizacion de informacion de trabajador", "updated", @employee.id, @employee.full_name, @employee.class.to_s
      redirect_to employees_path    
    else
      render :edit         
    end
  end

  def toggle_status
    @employee.change_status
    current_user.register_audit  @employee.tooltip_status +  " trabajador", "updated", @employee.id, @employee.full_name, @employee.class.to_s
    respond_to do |format|
      format.js
    end
  end

  def destroy
    @employee.inactive!
    redirect_to employees_path 
  end

  private

    def employee_params
      params.require(:user).permit(:phone, :email, :address, :name, :last_name, :date_of_birth, :gender, :role_id, :job_position, :laboratory_id)
    end

    def set_employee
      @employee = User.find(params[:id])
    end

    def roles
      @roles = Role.all
    end

    def laboratories
      @laboratories = Laboratory.all
    end
end 

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employees_table.html.erb
<div class="material-datatables">
  <table
    id="employee-datatable"
    class="table table-hover sical-data-table"
    data-placeholder="Buscar Empleados"
  >
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Correo</th>
        <th>Rol</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.role.name %></td>
          <td>
            <%= link_to employee_path(employee),
              class: "btn btn-info btn-sm #{current_user.can_view(@controller) ? '' : 'disabled'}",
              data: { "toggle" => "tooltip" },
              title: "Ver"  do
            %>
              <i class="fa fa-eye" aria-hidden="true"></i>
            <% end %>
            <%= link_to edit_employee_path(employee),
              class: "btn btn-success btn-sm #{current_user.can_edit(@controller) ? '' : 'disabled'}",
              data: { "toggle" => "tooltip" },
              title: "Editar" do
            %>
              <i class="fa fa-pencil" aria-hidden="true"></i>
            <% end %>
            <%= link_to toggle_status_employee_path(employee),
              id: "employee-lock-#{employee.id}",
              class: "btn btn-danger btn-sm #{current_user.can_delete(@controller) ? '' : 'disabled'}",
              data: { toggle: "tooltip" },
              title: "#{employee.tooltip_status}",
              method: :put,
              remote: true do
            %>
              <% if employee.status == "active" %>
               <i class="fa fa-unlock" aria-hidden="true"></i>
              <% else %>
                <i class="fa fa-lock" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/_form.html.erb
<%= form_for employee,
  url: path,
  method: method,
  :html => {
    class: "form-horizontal validate sical-form sical-form-validated",
    id: "employee-form"
  } do |f| %>
  <% if @employee.errors.any? %>
    <% @employee.errors.full_messages.each do |m| %>
      <div class="alert alert-danger">
        <a
           href="#"
           class="close"
           data-dismiss="alert"
           aria-label="close"
           title="close">
          ×
        </a>
        </button>
        <span>
          <b> Error - </b> <%= m %>
        </span>
      </div>
    <% end %>
  <% end %>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :Nombre %>
    </div>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :name, class: "form-control", required: "required" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :Apellido %>
    </div>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :last_name,
        class: "form-control",
        required: "required"
      %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :Correo_Electrónico%>
    </div>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :email,
        class: "form-control",
        email: "true",
        required: "required"
      %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :Dirección %>
    </div>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :address, class: "form-control", required: "required" %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :Teléfono %>
    </div>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :phone,
        class: "form-control only-numbers",
        minLength: "7",
        maxLength: "9",
        required: "required"
      %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :Fecha_de_Nacimiento %>
    </div>
    <div class="date col-md-9 input-wrapper">
      <div class="input-group sical-input-group">
        <%= f.text_field :date_of_birth,
            value: employee.date_of_birth ? employee.date_of_birth.strftime("%d/%m/%Y") : "",
            class: "form-control sical-datepicker",
            required: "required",
            date: true,
            birth: true,
            onlyAdult: true
        %>
        <div class="input-group-addon">
          <i class="fa fa-calendar"></i>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :Sexo %>
    </div>
    <div class="col-md-9 input-wrapper">
      <div class="employee-gender-options">
        <% User.genders.keys.each do |gender|  %>
          <%= f.label gender.capitalize,
              class: "radio form-check-label sical-radio-button #{employee.gender == gender ? "checked" : ""}" do
          %>
          <%= f.radio_button :gender,
              gender,
              class: "form-check-input sical-input-radio-button",
              required: "required"
          %>
            <span class="icons">
              <span class="first-icon fa fa-circle-o"></span>
              <span class="second-icon fa fa-dot-circle-o"></span>
            </span>
            <%= t("activerecord.attributes.employee.gender.#{gender}") %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :laboratorio %>
    </div>
    <div class="col-md-9 input-wrapper">
      <%= f.collection_select :laboratory_id,
          @laboratories,
          :id,
          :name,
          { selected: current_user.laboratory ? current_user.laboratory.id : f.object.laboratory_id },
          class: "form-control",
          required: "required",
          disabled: !current_user.admin?
      %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-3 col-fom-label">
      <%= f.label :rol %>
    </div>
    <div class="col-md-9 input-wrapper">
      <%= f.collection_select :role_id,
          Role.own_per_user(current_user),
          :id,
          :name,
          {},
          class: "form-control",
          required: "required"
      %>
    </div>
  </div>
  <div class="sical-form-buttons">
    <div class="text-center">
      <%= link_to "Cancelar", employees_path, class: "btn btn-primary sical-btn-cancel" %>
      <%= f.submit "Guardar",
          class: "btn btn-primary sical-submit-btn",
          data: {
            disable_with: 'Please Wait...',
          }
      %>
    </div>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="card">
  <div class="content">
    <div class="header card-header-text employees-header">
      <h1 class="page-header title employee-card-title">
        <span>Empleado </span>
        <small>Edicion</small>
      </h1>
    </div>
    <%= render 'form',
        employee: @employee,
        method: :put,
        path: employee_path
    %>
  </div>
</div>

app/views/employees/index.html.erb
<section class="employees-index">
  <div class="card">
    <div class="content">
      <div class="header card-header-text sical-card-header">
        <h1 class="sical-card-title">
          Empleados
        </h1>
        <div>
          <%= link_to 'Nuevo Empleado',
            new_employee_path,
            class: "btn btn-primary align-right #{current_user.can_create(@controller) ? '' : 'disabled'}"
          %>
        </div>
      </div>
      <div class="employees-content">
        <div id="employees-table">
          <%= render 'employees_table', employees: @employees %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/employees/new.html.erb
<div class="card">
  <div class="content">
    <div class="header card-header-text sical-card-header">
      <h1 class="page-header title sical-card-title">
        <span>Empleados </span>
        <small>Nuevo</small>
      </h1>
    </div>
    <%= render 'form',
        employee: @employee,
        method: :post,
        path: employees_path
    %>
  </div>
</div>

app/views/employees/show.html.erb
<div class="card">
  <div class="content">
    <div class="header card-header-text sical-card-header">
      <h1 class="page-header title sical-card-title">
        <span>Empleado </span>
        <small>Ver</small>
      </h1>
    </div>
    <div class="form-horizontal validate sical-form sical-form-validated">
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Nombre</label>
        <div class="col-md-9">
          <%= @employee.name %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Apellido</label>
        <div class="col-md-9">
          <%= @employee.last_name %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Correo Electrónico</label>
        <div class="col-md-9">
          <%= @employee.email %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Dirección</label>
        <div class="col-md-9">
          <%= @employee.address %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Teléfono </label>
        <div class="col-md-9">
          <%= @employee.phone %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Fecha de Nacimiento </label>
        <div class="col-md-9">
          <% if @employee.date_of_birth %>
            <%= @employee.date_of_birth.strftime("%d/%m/%Y") %>
          <% end %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Sexo </label>
        <div class="col-md-9">
          <% if @employee.gender == 'male' %>
            <span>Masculino</span>
          <% else %>
            <span>Femenino</span>
          <% end %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Rol </label>
        <div class="col-md-9">
          <%= @employee.role.name %>
        </div>
      </div>
      <div class="form-group row">
        <label class="col-md-3 col-form-label">Laboratorio </label>
        <div class="col-md-9">
          <%= @employee.laboratory.name %>
        </div>
      </div>
      <div class="form-group">
        <div class="text-center">
          <%= link_to "Regresar",
              employees_path,
              class: "btn btn-primary sical-btn-cancel"
          %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/toggle_status.js.erb
(function() {
  $(function() {
    var $currentLock = $('#employee-lock-<%= @employee.id %>');
    var status = "<%= @employee.status %>";

    toggleLockStatus($currentLock, status);
  });
})();