config/routes.rb
Rails.application.routes.draw do
  get 'session_google/create'

  get 'session_google/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
    devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  #WEB ROUTES
  get '200.162.7.62.nip.io:3000/auth/:provider/callback', to: 'session_google#create'
  get '200.162.7.62.nip.io:3000/auth/failure', to: redirect('/')
  get '200.162.7.62.nip.io:3000/signout', to: 'session_google#destroy', as: 'signout'

  get '/dashboard/index', to: 'dashboard#index', as: 'dash'

  resources :session_google, only: [:create, :destroy]
  
  resources :roles do
    put 'toggle_status', on: :member
  end
  resources :laboratories do
    put 'toggle_status', on: :member
  end
  resources :clients do
    put 'toggle_status', on: :member
  end
  resources :employees do
    put 'toggle_status', on: :member
  end
  resources :inventories do
    put 'toggle_status', on: :member
  end
  resources :supplies do
    put 'toggle_status', on: :member
  end  
  resources :sample_methods do
    put 'toggle_status', on: :member
  end
  resources :classified_services do
    get 'work_check', on: :member
    put 'work_check_update', on: :member
  end
  resources :services do
    get 'search', on: :collection
    get 'work_check', on: :member
    put 'work_check_update', on: :member
    get 'service_end', on: :member
    put 'service_end_update', on: :member
  end
  
  resources :users
  resources :contracts
  resources :sample_methods
  resources :quotations do
    post 'get_sample_methods', on: :collection
    post 'get_sample_method', on: :collection
  end
  resources :requests
  resources :results
  resources :work_orders
  resources :logs
  resources :service_quotations
  resources :services
  resources :sample_categories do
    put 'toggle_status', on: :member
  end
  resources :check_services do
    get 'search', on: :collection
  end
  resources :classified_services
  resources :work_classified_services do 
    get 'values', on: :member
  end
  resources :historic_custodies 
  resources :system_parameters
  resources :contact_us
  resources :audits

end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
  include ApplicationHelper
	
  validates :name, presence: true
  validates :phone, length: { in: 7..9}
  validates :phone, numericality: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  mount_uploader :header_image, ImageUploader
  mount_uploader :internal_report, DocumentUploader
  mount_uploader :accredited_report, DocumentUploader
  mount_uploader :normal_report, DocumentUploader
  #before_save :update_header_image_attributes

  has_many :sample_methods
  has_many :requests
  has_many :contact_us
  has_many :services, dependent: :destroy
  has_many :inventories, dependent: :destroy
  has_many :supplies, dependent: :destroy
  has_many :users, dependent: :destroy
  has_many :roles, dependent: :destroy
  has_many :sample_categories, dependent: :destroy

  enum status: [:active, :inactive]

  
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController

  before_action :set_laboratory, only: [:show, :edit, :update, :destroy, :toggle_status]

  def index
    @laboratories = Laboratory.all
  end

  def new
    @laboratory = Laboratory.new
  end

  def show
  end

  def create
    @laboratory = Laboratory.new laboratory_params
    if @laboratory.save
      current_user.register_audit "Creacion de laboratorio", "added", @laboratory.id, @laboratory.name, @laboratory.class.to_s
      redirect_to laboratories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @laboratory.assign_attributes laboratory_params
    if @laboratory.save
      current_user.register_audit "Actualizacion de informacion de laboratorio", "updated", @laboratory.id, @laboratory.name, @laboratory.class.to_s
      redirect_to laboratories_path
    else
      render :edit
    end
  end

  def toggle_status
    @laboratory.change_status
    current_user.register_audit  @laboratory.tooltip_status +  " laboratorio", "updated", @laboratory.id, @laboratory.name, @laboratory.class.to_s
    respond_to do |format|
      format.js
    end
  end

  private
    def laboratory_params
      params.require(:laboratory).permit(:name, :phone, :email, :address, :description, :header_image,:internal_report,:accredited_report,:normal_report)
    end

    def set_laboratory
      @laboratory = Laboratory.find params[:id]
    end

end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/views/laboratories/_form.html.erb
<%= form_for laboratory, url: path, method: method, :html => { class: "form-horizontal validate sical-form sical-form-validated" } do |f| %>
  <% if @laboratory.errors.any?%>
    <% @laboratory.errors.full_messages.each do |m| %>
      <p><%= m %></p>
    <% end %>
  <% end %>
  <div class="form-group row">
    <%= f.label :Nombre, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :name, class: "form-control", required:"required" , maxlength:"80" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Correo  , class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :email, class: "form-control ", required:"required" ,maxlength:"60", email: true %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Dirección, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :address, class: "form-control ", required:"required" , maxlength:"60" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Teléfono, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.text_field :phone, class: "form-control only-numbers",maxlength:"9",required:"required" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Descripción, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.text_area :description, class: "form-control item-description", rows: "5", required:"required" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Logo, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.file_field :header_image %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Reporte_Interno, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.file_field :internal_report %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Reporte, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.file_field :normal_report %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :Reporte_Acreditado, class: "col-md-3 col-form-label" %>
    <div class="col-md-9 input-wrapper">
      <%= f.file_field :accredited_report %>
    </div>
  </div>
  <div class="sical-form-buttons">
    <div class="text-center">
      <%= link_to "Cancelar", laboratories_path, class: "btn btn-primary sical-btn-cancel" %>
      <%= f.submit "Guardar", class: "btn btn-primary", data: {disable_with: 'Please Wait...'}  %>
    </div>
  </div>
<% end %>

app/views/laboratories/_laboratories_table.html.erb
<div class="material-datatables">
  <table id="laboratory-table" class="table table-no-bordered table-hover sical-data-table" data-placeholder="Buscar Laboratorios">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Teléfono</th>
        <th>Correo</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% laboratories.each do |laboratory| %>
        <tr>
          <td><%= laboratory.name %></td>
          <td><%= laboratory.phone %></td>
          <td><%= laboratory.email %></td>
          <td>
            <%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, laboratory_path(laboratory), class: "btn btn-info btn-sm #{current_user.can_view(@controller) ? '' : 'disabled'}", data: { "toggle" => "tooltip" }, title: "Ver" %>
            <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_laboratory_path(laboratory), class: "btn btn-success btn-sm #{current_user.can_edit(@controller) ? '' : 'disabled'}", data: { "toggle" => "tooltip" }, title: "Editar" %>
            <%= link_to toggle_status_laboratory_path(laboratory), id: "laboratory-lock-#{laboratory.id}", class: "btn btn-danger btn-sm #{current_user.can_delete(@controller) ? '' : 'disabled'}", data: { "toggle" => "tooltip" }, title: "#{laboratory.tooltip_status}", method: :put, remote: true do %>
              <% if laboratory.status == "active" %>
                <i class="fa fa-unlock" aria-hidden="true"></i>
              <% else %>
                <i class="fa fa-lock" aria-hidden="true"></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/laboratories/_search.html.erb
<%= form_tag "#{}", class: "validate", method: :get, remote: true do %>
  <div class="row form-group">
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :name, "Nombre", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :name, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-5">
      <div class="col-sm-4">
        <%= label_tag :email, " Email", class: "control-tag" %>
      </div>
      <div class="col-sm-8">
        <%= text_field_tag :email, nil, class: "form-control" %>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="col-md-12">
        <input class="btn btn-success" type="submit" value="Buscar">
      </div>
    </div>
  </div>
<% end %>

app/views/laboratories/edit.html.erb
<div class="card">
  <div class="content">
    <div class="header card-header-text laboratory-header">
      <h1 class="page-header title laboratory-card-title">Laboratorio <small>Edición</small></h1>
    </div>
    <%= render 'form', laboratory: @laboratory, method: :put, path: laboratory_path %>
  </div>
</div>

app/views/laboratories/index.html.erb
<section class="laboratories-index">
  <div class="card">
    <div class="content">
      <div class="header card-header-text sical-card-header">
        <h1 class="sical-card-title">
          Laboratorios
        </h1>
        <div>
          <%= link_to 'Nuevo Laboratorio', new_laboratory_path, class: "btn btn-primary align-right #{current_user.can_create(@controller) ? '' : 'disabled'}"  %>
        </div>
      </div>
      <div class="laboratories-content">
        <div id="laboratories-table">
          <%= render 'laboratories_table', laboratories: @laboratories %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/laboratories/new.html.erb
<div class="card">
  <div class="content">
    <div class="header card-header-text sical-card-header">
      <h1 class="page-header title sical-card-title">Laboratorio <small>Nuevo</small></h1>
    </div>
    <%= render 'form', laboratory: @laboratory, method: :post, path: laboratories_path %>
  </div>
</div>

app/views/laboratories/show.html.erb
<div class="card">
  <div class="content">
    <div class="header card-header-text laboratory-header">
      <h1 class="page-header title laboratory-card-title">Laboratorio <small>Ver</small></h1>
    </div>
    <div class="form-horizontal validate sical-form sical-form-validated">
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Nombre</label>
        <div class="col-md-9">
          <%= @laboratory.name %>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Correo Electrónico</label>
        <div class="col-md-9">
          <%= @laboratory.email %>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Dirección</label>
        <div class="col-md-9">
          <%= @laboratory.address %>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Teléfono</label>
        <div class="col-md-9">
          <%= @laboratory.phone %>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Descripción</label>
        <div class="col-md-9">
          <%= @laboratory.description %>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Logo</label>
        <div class="col-md-9">
          <%= link_to "Descarga", @laboratory.header_image_url, class: "btn btn-info btn-sm" %></td>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Reporte Interno</label>
        <div class="col-md-9">
          <%= link_to "Descarga", @laboratory.internal_report_url, class: "btn btn-info btn-sm" %></td>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Reporte</label>
        <div class="col-md-9">
          <%= link_to "Descarga", @laboratory.normal_report_url, class: "btn btn-info btn-sm"%></td>
        </div>
      </div>
      <div class="form-group row">
        <label class= "col-md-3 col-form-label">Reporte Acreditado</label>
        <div class="col-md-9">
          <%= link_to "Descarga", @laboratory.accredited_report_url, class: "btn btn-info btn-sm" %></td>
        </div>
      </div>
      <div class="sical-form-buttons">
        <div class="text-center">
          <%= link_to "Regresar", laboratories_path, class: "btn btn-primary sical-btn-cancel" %>
        </div>
      </div>
    </div>   
  </div>
</div>

app/views/laboratories/toggle_status.js.erb
(function() {
  $(function() {
    var $currentLock = $('#laboratory-lock-<%= @laboratory.id %>');
    var status = "<%= @laboratory.status %>";

    toggleLockStatus($currentLock, status);
  });
})();