config/routes.rb
Rails.application.routes.draw do
  get 'session_google/create'

  get 'session_google/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
    devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  #WEB ROUTES
  get '200.162.7.62.nip.io:3000/auth/:provider/callback', to: 'session_google#create'
  get '200.162.7.62.nip.io:3000/auth/failure', to: redirect('/')
  get '200.162.7.62.nip.io:3000/signout', to: 'session_google#destroy', as: 'signout'

  get '/dashboard/index', to: 'dashboard#index', as: 'dash'

  resources :session_google, only: [:create, :destroy]
  
  resources :roles do
    put 'toggle_status', on: :member
  end
  resources :laboratories do
    put 'toggle_status', on: :member
  end
  resources :clients do
    put 'toggle_status', on: :member
  end
  resources :employees do
    put 'toggle_status', on: :member
  end
  resources :inventories do
    put 'toggle_status', on: :member
  end
  resources :supplies do
    put 'toggle_status', on: :member
  end  
  resources :sample_methods do
    put 'toggle_status', on: :member
  end
  resources :classified_services do
    get 'work_check', on: :member
    put 'work_check_update', on: :member
  end
  resources :services do
    get 'search', on: :collection
    get 'work_check', on: :member
    put 'work_check_update', on: :member
    get 'service_end', on: :member
    put 'service_end_update', on: :member
  end
  
  resources :users
  resources :contracts
  resources :sample_methods
  resources :quotations do
    post 'get_sample_methods', on: :collection
    post 'get_sample_method', on: :collection
  end
  resources :requests
  resources :results
  resources :work_orders
  resources :logs
  resources :service_quotations
  resources :services
  resources :sample_categories do
    put 'toggle_status', on: :member
  end
  resources :check_services do
    get 'search', on: :collection
  end
  resources :classified_services
  resources :work_classified_services do 
    get 'values', on: :member
  end
  resources :historic_custodies 
  resources :system_parameters
  resources :contact_us
  resources :audits

end

app/models/quotation.rb
class Quotation < ApplicationRecord
  validates :total, numericality: { :greater_than_or_equal_to => 0 }
  enum status: [:pending, :revised]        
end

app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
	
  before_action :set_service, only: [:new, :edit, :update, :destroy, :show]
  before_action :set_sample_methods, only: [:edit, :update]
  before_action :set_laboratories, only: [:edit, :new]
  before_action :sample_categories, only: [:new, :create, :edit, :update, :show]
  before_action :employees , only: [:edit]
  before_action :set_users_belongs_to_laboratory, only: [:edit, :new]

  def index

    # EMPLOYEE - Sees all the new requests (Concurrency kek)
    @initial_unfunded = Service.quotations_without_funded current_user
    # USER - Accepts the fist quotation 
    @initial_funded = Service.quotations_with_initial_funded current_user
    # EMPLOYEE - Make the adjustments after the custody chain
    @services_to_adjusts = Service.passed_classification current_user
    # USER - Accept the final adjustment of the Service
    @adjusted_services = Service.adjusted_by_lab_leader current_user
    # EMPLOYEE - Contract Generation. Assign work orders
    @contract_bound_services = Service.contract_bound current_user    
    # In WorkOrder cards
    @services_with_engagements = Service.services_with_engagements current_user
  end

  def new
  end

  def show
  end

  def create
  end

  def edit   
  end

  def get_sample_methods
    respond_to do |format|
      format.json {
        render json: {sample_methods: SampleCategory.find(params[:id]).sample_methods}
      }
    end
  end

  def get_sample_method
    respond_to do |format|
      format.json {
        render json: {sample_method: SampleMethod.find(params[:id])}
      }
    end
  end

  def update
    begin
    if @service.accepted_contract?
      @service.asssign_workers_work params, current_user
      @service.set_work_flow current_user
      current_user.register_audit "Asignacion de trabajador a orden de trabajo", "updated", @service.id, "Trabajo", @service.class.to_s
      redirect_to  quotations_path
    else
      @service.assign_attributes quotation_params
      if @service.save
        current_user.register_audit "Validacion del estado de la orden de trabajo", "updated", @service.id, "Trabajo", @service.class.to_s
        @service.set_work_flow(current_user)
        redirect_to  quotations_path
      else
        render :edit
      end 
    end       
    rescue Exception => e
      p e.to_s
      redirect_to quotations_path      
    end

  end

  def toggle_status
    @laboratory.change_status
    respond_to do |format|
      format.js
    end
  end  

  private 

    def quotation_params
      params.require(:service).permit(:laboratory_id, :valid_initial_funded, :valid_classified, :subject, :pick_up_date, :engagement, :total, sample_preliminaries_attributes: sample_preliminaries, sample_processeds_attributes: sample_processeds)
    end

    def sample_processeds
      [:id, :category_id, :description, :pucp_code, :client_code, :amount, :unit_cost, :subtotal_cost, :discount,  :sample_method_id, :user_id, sample_features_attributes: sample_features]
    end

    def sample_features
      [:id, :value, :description]
    end

    def sample_preliminaries
      [:id, :name, :quantity, :description, :sample_method_id, :sample_category_id, :unit_cost]
    end

    def set_service
      @service = Service.find params[:id]
    end

    def set_sample_methods
      @sample_methods = SampleMethod.all
    end

    def set_laboratories
      @laboratories = Laboratory.all
    end

    def sample_categories
      @sample_categories = SampleCategory.own_per_user current_user
    end    

    def employees
      @employees = User.own_per_user(current_user).employee
    end

    def set_users_belongs_to_laboratory
      @users = User.own_per_user(current_user)
    end
end

app/helpers/quotations_helper.rb
module QuotationsHelper
end

app/views/quotations/_client_sample_preliminary_fields.html.erb
<tr class="sample-preliminaries-row">
  <td class="sample-preliminaries-name-wrapper">
    <%= f.text_field :name, readonly: true , class: "form-control"%>
  </td>

  <td class="sample-preliminaries-category-wrapper">
    <%= f.collection_select :sample_category_id, @sample_categories, :id, :name, {}, {class: "form-control", disabled: true} %>
  </td>
  <td class="sample-preliminaries-method-wrapper">
    <%= f.collection_select :sample_method_id, @sample_methods, :id, :name, {}, {class: "form-control", disabled: true} %>
  </td>
  <td class="sample-preliminaries-quantity-wrapper">
    <%= f.text_field :quantity , readonly: true, class: "form-control", id: "sample-preliminaries-quantity-#{f.object.id}" %>
  </td>
  <td class="sample-preliminaries-unit-cost-wrapper">
    <%= f.text_field :unit_cost, readonly: true, class: "form-control", id: "sample-preliminaries-unit-cost-#{f.object.id}", value: f.object.unit_cost %>
  </td>
  <td class="sample-preliminaries-sub-total-wrapper">
    <input type="text" class="form-control" id="sample-preliminaries-sub-total-<%= f.object.id %>" readonly="true" value="<%= f.object.unit_cost ? f.object.unit_cost * f.object.quantity : 0 %>">
  </td>
</tr>

app/views/quotations/_engagement.html.erb
Quien suscribe, <%= current_user.name %> <br>
<%= SystemParameter.terms_and_condition.first.description %>
<br>

app/views/quotations/_funded_samples.html.erb
<div id="costeo" class="tabcontent">
  <table class="table table-no-bordered table-hover">
    <thead>
      <th class="funded-sample-table-header is-larger">Nombre</th>
      <th class="funded-sample-table-header is-medium">Categoría</th>
      <th class="funded-sample-table-header is-large">Método</th>
      <th class="funded-sample-table-header is-small">Cantidad</th>
      <th class="funded-sample-table-header is-medium">Precio</th>
      <th class="funded-sample-table-header is-medium">Subtotal</th>
    </thead>
    <tbody>
      <% if current_user.client? || @service.can_see_quotation_adjust %>
        <%= f.fields_for :sample_preliminaries do |s_p| %>
          <%= render 'client_sample_preliminary_fields', f: s_p %>
        <% end %>
      <% else %>
        <%= f.fields_for :sample_preliminaries do |s_p| %>
          <%= render 'sample_preliminary_fields', f: s_p %>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="col-md-5 offset-md-7 ">
    <div class="form-group row">
      <div class="col-md-8 text-center">
        <strong>Total</strong>
      </div>
      <div class="text-center" style="width: 32%">
        <%= f.text_field :total, readonly: true, class: "form-control", id: "quotation-total-input", value: f.object.total ? f.object.total : '0.0' %>
      </div>
    </div>
  </div>

  <% if current_user.client? and @service.initial_funded? %>
    <div class="form-group row">
      <div class="col-md-3 col-fom-label">
        <%= f.label :Confirmación %>
      </div>
      <div class="col-md-4">
        <label class="radio form-check-label sical-radio-button">
          <span class="icons">
            <span class="first-icon fa fa-circle-o"></span>
            <span class="second-icon fa fa-dot-circle-o"></span>
          </span>
          <input
            id="accepted"
            type="radio"
            class="form-check-input"
            data-toggle="radio"
            name="service[valid_initial_funded]"
            value="true"
          >
          Aceptado
        </label>
        <label class="radio form-check-label sical-radio-button">
          <span class="icons">
            <span class="first-icon fa fa-circle-o"></span>
            <span class="second-icon fa fa-dot-circle-o"></span>
          </span>
          <input
            id="rejected"
            type="radio"
            class="form-check-input"
            data-toggle="radio"
            name="service[valid_initial_funded]"
            value="false"
          >
          No Aceptado
        </label>
      </div>
    </div>
    <div class=" engagement-observation hide ">
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :observaciones %> 
        </div>
        <div class="col-md-9">
          <%= f.text_field :client_quotation_observation, class: "form-control", maxlength:"50" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/quotations/_quotation_accepted.html.erb
<div id="terminos-condiciones" class="tabcontent">
  <% if current_user.client? and service.accepted_adjust? %>
    <div >
      <h4> Compromiso </h4>
    </div>
    <div class="engagement ">
      <%= render 'engagement' %>
    </div>
    <br>
    <div class="form-group row">
      <div class="col-md-3 col-fom-label">
        <%= f.label :Validación %>
      </div>
      <div class="col-md-9">
        <label class="radio form-check-label sical-radio-button">
          <span class="icons">
            <span class="first-icon fa fa-circle-o"></span>
            <span class="second-icon fa fa-dot-circle-o"></span>
          </span>
          <input
            id="accepted"
            type="radio"
            class="form-check-input"
            data-toggle="radio"
            name="service[engagement]"
            value="true"
          >
          Aceptado
        </label>
        <label class="radio form-check-label sical-radio-button">
          <span class="icons">
            <span class="first-icon fa fa-circle-o"></span>
            <span class="second-icon fa fa-dot-circle-o"></span>
          </span>
          <input
            id="rejected"
            type="radio"
            class="form-check-input"
            data-toggle="radio"
            name="service[engagement]"
            value="false"
          >
          No Aceptado
        </label>
      </div>
    </div>
    <div class=" engagement-observation hide ">
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :observaciones %> 
        </div>
        <div class="col-md-9">
          <%= f.text_field :client_quotation_observation, class: "form-control", maxlength:"50" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/quotations/_quotation_adjusted.html.erb
<% if @service.can_see_quotation_adjust %>
  <div id="adjust_cost" class="tabcontent">
    <%= render 'add_nested_elements', title: "Muestras", button_message: "", editable: false, f: f, 'association_insert_node': '.service-adjust', fields: :sample_processeds, partial: 'sample_processed_fields' %>
  </div>
<% end %>

app/views/quotations/_quotation_contract.html.erb
<div id="contract" class="tabcontent">
  <br></br>
  <%= link_to "Descargar Contrato", File.join("/contratos", "#{@service.id}.pdf") %>
</div>

app/views/quotations/_quotation_employee.html.erb
<div class="nested-fields">
  <div class="form-group row">
    <%= f.label :Codigo_cliente, class: "col-md-3 col-fom-label" %>
     <div class="col-md-9">
        <%= f.text_field :client_code,class: "form-control", maxLength:"8", required: "required" %>
    </div>
  </div>
</div>

app/views/quotations/_quotation_worker.html.erb
<div id="employee-assign" class="tabcontent">
  <table class="table table-hover sical-data-table sical-data-table"  data-placeholder="Buscar Muestra">
    <thead>
      <th>Código de muestra</th>
      <th>Categoría</th>
      <th>Método</th>
      <th>Acreditado</th>
      <th>Asignación</th>
    </thead>
    <tbody>
    <% @service.sample_processeds.each.with_index(1) do |sample_processed, index| %>
        <tr>
          <td><%= sample_processed.description %></td>
          <td><%= sample_processed.sample_category.name %></td>
          <td><%= sample_processed.sample_method_name %></td>
          <td><% if sample_processed.sample_method.accredited? %>
            Si
        <% else %> 
            No 
        <% end %></td> 
          <td><%= f.collection_select :id, @employees,:id, :name,{}, {name: "selected_employee_#{index}"} %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/quotations/_quotations_table.html.erb
<div class="content">
  <div class="material-datatables">
    <table class="table table-hover sical-data-table sical-data-table" data-placeholder="Buscar Solicitudes">
      <thead>
        <tr>
          <th>Asunto</th>
          <th>Fecha de Recojo</th>
          <th>Estado</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% quotations.each do |quotation| %>
          <tr>
            <td><%= quotation.subject %></td>
            <td><%= quotation.pick_up_date.strftime("%d/%m/%Y")%></td>
            <td><%= quotation.status %></td>
            <td>
              <%#= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, edit_quotation_path(quotation), class: "btn btn-success btn-sm", data: { "toggle" => "tooltip" }, title: "Editar" %>
              <%#= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, quotation_path(quotation), class: "btn btn-info btn-sm", data: { "toggle" => "tooltip" }, title: "Ver" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/quotations/_sample_processed_fields.html.erb
<div class="nested-fields">
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Código del Cliente</label>
     <div class="col-md-9">
        <%= f.text_field :client_code, class: "form-control", readonly: true %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Código PUCP</label>
     <div class="col-md-9">
        <%= f.text_field :pucp_code, class: "form-control", readonly: true%>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Categoría</label>
     <div class="col-md-9">
      <%= f.collection_select :sample_category_id, @sample_categories, :id, :name, {}, {class: "form-control", disabled: true} %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Descripción</label>
     <div class="col-md-9">
        <%= f.text_field :description, class: "form-control", readonly: true %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Métodos de Muestra</label>
     <div class="col-md-9">
        <%= f.collection_select :sample_method_id, @sample_methods, :id, :name, {}, {class: "form-control", disabled: true} %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Costos </label>
    <div class="col-md-9">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Costo Unitario</th>
            <th>Subtotal</th>
            <th>Descuento</th>
            <th>Monto</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= f.text_field :unit_cost, readonly: true ,class: "form-control", value: f.object.sample_method.unit_cost %>
            </td>
            <td>
              <%= f.text_field :amount, readonly: true , class: "form-control", value: f.object.handle_subtotal ? f.object.handle_subtotal : '0.0' %>
            </td>
            <td>
              <%= f.text_field :discount, onlyTwoDecimals: true, class: "form-control only-numbers quotation-discount-field", readonly: current_user.category == 'client' %>
            </td>
            <td>
              <%= f.text_field :subtotal_cost, readonly: true , class: "form-control", value: f.object.handle_subtotal ? f.object.handle_subtotal : '0.0' %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/quotations/_setted_information.html.erb
<div id="informacion-general" class="tabcontent" style="display: block;">
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Cliente</label>
     <div class="col-md-9">
        <%= @service.client.name %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Laboratorio</label>
     <div class="col-md-9">
        <%= @service.laboratory.name %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Fecha Próxima de Recojo</label>
     <div class="col-md-9">
        <%= @service.pick_up_date.strftime("%d/%m/%Y")%>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Asunto</label>
     <div class="col-md-9">
        <%= @service.subject %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Muestra(s)</label>
    <div class="col-md-9">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Descripción</th>
          </tr>
        </thead>
        <tbody>
          <% @service.sample_preliminaries.each do |sp|%>
            <tr>
              <td><%= sp.name %></td>
              <td><%= sp.quantity %></td>
              <td><%= sp.description %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/quotations/_show_contract.html.erb
<div id="contract" class="tabcontent">
  <% if current_user.employee?  and service.accepted_contract? %>
    <div class="form-group row">
      <label class= "col-md-3 col-form-label">Ver Contrato</label>
      <div class="col-md-9">
         <td><%= link_to "Descarga", File.join("/contratos", "ContratoServ-#{@service.id}.pdf"), class: "btn btn-info btn-sm" %></td>
      </div>
    </div>
  <% end %>
</div>

app/views/quotations/edit.html.erb
<div class="card">
  <div class="content">
    <div class="header card-header-text sical-card-header">
      <h2 class="page-header sical-card-title">Proforma</h2>
    </div>
    <div class="tab">
      <button class="tablinks active" onclick="openSection(event, 'informacion-general')">Informacion General</button>
      <button class="tablinks" onclick="openSection(event, 'costeo')">Costeo</button>
      <% if @service.can_see_quotation_adjust %>
        <button class="tablinks" onclick="openSection(event, 'adjust_cost')">Ajuste de costeo</button>
      <% end %>
      <% if current_user.client? and @service.accepted_adjust? %>
        <button class="tablinks" onclick="openSection(event, 'terminos-condiciones')">Términos y condiciones</button>
      <% end %>
      <% if current_user.employee? and @service.accepted_contract? %>
        <button class="tablinks" onclick="openSection(event, 'contract')">Contrato</button>
        <button class="tablinks" onclick="openSection(event, 'employee-assign')">Orden de trabajo</button>
      <% end %>
    </div>

    <%= nested_form_for @service, url: quotation_path, method: :put do |f| %>
      <%= render 'setted_information', service: @service, f: f %>
      <%= render 'funded_samples', service: @service, f: f %>
      <%= render 'quotation_accepted', service: @service, f: f %>
      <%= render 'quotation_adjusted', service: @service, f: f %>
      <%= render 'quotation_worker', service: @service, f: f %>

      <%= render 'show_contract', service: @service, f: f %>
      <div class="sical-form-buttons">
        <div class="text-center">
          <%= link_to "Cancelar", quotations_path, class: "btn btn-primary sical-btn-cancel" %>
          <%= f.submit "Guardar", class: "btn btn-primary", data: {disable_with: 'Please Wait...'}  %>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/quotations/index.html.erb
<section class="requests-index">
  <div class="card">
    <div class="content">
      <div class="header card-header-text sical-card-header">
        <h1 class="sical-card-title">
          Proformas
        </h1>
      </div>
      <div class="sical-content">
        <div class="sub-section-cards">
          <% if current_user.employee?%>
            <div class="col-lg-4 sub-section-card is-unread-card">
              <%= render 'sub_section_card', elements: @initial_unfunded, title: "Servicios sin Costear", controller: "quotation" %>
            </div>
            <div class="col-lg-4 sub-section-card is-read-card">
              <%= render 'sub_section_card', elements: @services_to_adjusts, title: "Servicios por Ajustar", controller: "quotation" %>
            </div>
            <div class="col-lg-4 sub-section-card is-read-card">
              <%= render 'sub_section_card', elements: @contract_bound_services, title: "Proformas aceptadas", controller: "quotation" %>
            </div>
          <% else %>
            <div class="col-md-6 sub-section-card is-read-card">
              <%= render 'sub_section_card', elements: @initial_funded, title: "Servicios Costeados", controller: "quotation" %>
            </div>
            <div class="col-md-6 sub-section-card is-read-card">
              <%= render 'sub_section_card', elements: @adjusted_services, title: "Servicios Ajustados", controller: "quotation" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>