config/routes.rb
Rails.application.routes.draw do
  get 'session_google/create'

  get 'session_google/destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
    devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "devise/sessions#destroy"
    authenticated :user do
      root 'dashboard#index'
    end

    unauthenticated do
      root 'devise/sessions#new'
    end
  end

  #WEB ROUTES
  get '200.162.7.62.nip.io:3000/auth/:provider/callback', to: 'session_google#create'
  get '200.162.7.62.nip.io:3000/auth/failure', to: redirect('/')
  get '200.162.7.62.nip.io:3000/signout', to: 'session_google#destroy', as: 'signout'

  get '/dashboard/index', to: 'dashboard#index', as: 'dash'

  resources :session_google, only: [:create, :destroy]
  
  resources :roles do
    put 'toggle_status', on: :member
  end
  resources :laboratories do
    put 'toggle_status', on: :member
  end
  resources :clients do
    put 'toggle_status', on: :member
  end
  resources :employees do
    put 'toggle_status', on: :member
  end
  resources :inventories do
    put 'toggle_status', on: :member
  end
  resources :supplies do
    put 'toggle_status', on: :member
  end  
  resources :sample_methods do
    put 'toggle_status', on: :member
  end
  resources :classified_services do
    get 'work_check', on: :member
    put 'work_check_update', on: :member
  end
  resources :services do
    get 'search', on: :collection
    get 'work_check', on: :member
    put 'work_check_update', on: :member
    get 'service_end', on: :member
    put 'service_end_update', on: :member
  end
  
  resources :users
  resources :contracts
  resources :sample_methods
  resources :quotations do
    post 'get_sample_methods', on: :collection
    post 'get_sample_method', on: :collection
  end
  resources :requests
  resources :results
  resources :work_orders
  resources :logs
  resources :service_quotations
  resources :services
  resources :sample_categories do
    put 'toggle_status', on: :member
  end
  resources :check_services do
    get 'search', on: :collection
  end
  resources :classified_services
  resources :work_classified_services do 
    get 'values', on: :member
  end
  resources :historic_custodies 
  resources :system_parameters
  resources :contact_us
  resources :audits

end

app/controllers/classified_services_controller.rb
class ClassifiedServicesController < ApplicationController
  before_action :set_service, only: [:edit,:update, :update, :destroy, :show]
  before_action :set_custody_order, only: [:work_check,:work_check_update, :destroy]
  before_action :set_custody_table, only: [:work_check]
  before_action :sample_categories, only: [:new, :create, :edit, :update, :show]

	def index
		@services_unclassified = Service.inital_funded_accepted current_user	
    @custody_order_to_check = CustodyOrder.custody_orders_to_check current_user      
	end

  def work_check
  end

	def edit
     @employees = User.own_per_user(current_user).employee		
	end

	def update   
   begin         
      @service.asssign_workers_custody params, current_user
      @service.set_work_flow current_user
      current_user.register_audit "Asignacion de trabajo", "updated", @service.id, "Trabajo", @service.class.to_s
      redirect_to  classified_services_path      
    rescue Exception => e      
      redirect_to classified_services_path      
    end
	end

  def work_check_update
    begin
      @custody_order.assign_attributes order_params
      if @custody_order.valid?
        @custody_order.handling_internal_process(current_user)
        current_user.register_audit "Revision de orden de trabajo", "updated", @custody_order.id, "Trabajo", @custody_order.class.to_s
        left_orders = CustodyOrder.custody_orders_per_service(@service).where.not(work_flow: :completed)
        if !left_orders.any?
          @service.handling_internal_process(current_user)
        end
        if @custody_order.to_rework?
          @custody_order.increment!(:nr_revision)
        end
        redirect_to classified_services_path
      else
        render :work_check
      end
    rescue Exception => e      
      redirect_to classified_services_path
    end
  end

  private

    def service_params
      params.require(:service).permit(:valid_classified,:laboratory_id, :user_id, :employee_id, :subject, :pick_up_date, sample_preliminaries_attributes: sample_preliminaries, sample_processeds_attributes: sample_processeds)
    end

    def order_params
      params.require(:custody_order).permit(:supervisor_id,:employee_id,:nr_revision,:sample_processed_id,:supervisor_observation,:valid_supervised)
    end    

    def sample_preliminaries
      [:id, :name, :quantity, :description]
    end

    def sample_processeds
      [:id, :sample_category_id, :description, :pucp_code, :client_code, sample_features_attributes: sample_features]
    end

    def sample_features
      [:id, :value, :description]
    end
        
    def set_service
      @service = Service.find params[:id]
      @custody_orders = CustodyOrder.where(service_id: params[:id])
    end

    def set_custody_order
      @custody_order = CustodyOrder.find params[:id]
      @sample_processed = @custody_order.sample_processed
      @service = @custody_order.sample_preliminary.service
    end

    def set_custody_table
      # Can be optimized by storing the dimensions in processed
      @rows = @sample_processed.amount        
      sample_id = @custody_order.sample_processed.sample_category_id
      method_id = @custody_order.sample_processed.sample_method_id
      cross_table = SampleCategoryxSampleMethod.where(sample_category_id: sample_id).where(sample_method_id: method_id).first
      @features = ChainFeature.where(sample_categoryx_sample_method_id: cross_table.id)
      @cols = @features.pluck(:concept)
    end

    def sample_categories
      @sample_categories = SampleCategory.own_per_user current_user
    end

    def laboratories
      @laboratories = Laboratory.all
    end

    def set_sample_methods
      @sample_methods = SampleMethod.all
    end

end

app/helpers/classified_services_helper.rb
module ClassifiedServicesHelper
end

app/views/classified_services/_classified_services.html.erb
<h3 class=" p-b-10 p-l-10 "><%= title %></h3>
<div class='mailbox-messages flex-1 content'>
   <div class="scroll ">
    <% if services_unclassified.empty?%>
      <div class="form-group row">
        No tiene mensajes sin leer.
      </div>
    <% else %>
      <% services_unclassified.each do |service| %>
        <div class="row ">
          <div class="col-md-2 text-center subject-date subject-border col-form-label">
            <h6>
              <%= service.created_at.strftime('%I:%M %p') %>
            </h6>
            <h6>
              <%= service.created_at.strftime('%^b %d') %>
            </h6>
          </div>
          <div class="col-md-8 col-form-label subject-border" >
            <h5>
              <strong>Asunto:</strong>
            </h5>
            <h6><%= service.subject %></h6>
          </div>
          <div class="col-md-2 text-center subject-date subject-border" >
            <br> 
            <h5 style="text-decoration: none;" ><%= link_to "Ver", edit_classified_service_path(service), data: { "toggle" => "tooltip" } %></h5> 
          </div>
        </div>
      <% end %>
    <% end %>
    <%#= link_to , id: 'more-messages', class: 'flex-container' do %>
      <span class=''></span><span class='text flex-1'>Ver todos los mensajes</span><span class='next'></span>
    <%# end %>
  </div>
</div>

app/views/classified_services/_custody_check.html.erb
<table class="table table-no-bordered table-hover">
  <thead>
    <th>Código PUCP</th>
    <th>Código Muestra Cliente</th>
    <th>Categoria de Muestra</th>
    <th>Método de Ensayo</th>
  </thead>
  <tbody>
  <tr>
    <td><%= sample.pucp_code %></td>
    <td><%= sample.client_code %></td>
    <td><%= sample.sample_category.name %></td>
    <td><%= sample.sample_method.name %></td>
  </tr>
  </tbody>
</table>
<%= render 'filling_up_sample_features' %>
 <div class="text-center">
  <h4>Observaciones</h4>
  <%= f.text_area :supervisor_observation, class: "form-control sical-text-area custody-chek-text-area", cols: "40", rows: "5" %>
</div>
<div class="checkbox form-check-label">
  <span class="icons">
    <span class="first-icon fa fa-square"></span>
    <span class="second-icon fa fa-check-square "></span>
  </span>
  <%= f.label :Aprobado? %>
  <%= f.check_box :valid_supervised, class: "form-check-input" %>
</div>

app/views/classified_services/_custody_order_to_check.html.erb
 <%= form_for @custody_order, url: work_check_update_classified_service_path, :wrapper => false,  method: :put do |f| %>
  <div id="service" class="tabcontent" style="display: block;">
    <h3>Información</h3>
    <%= render 'show_basic_information', service: @service, f: f %>
  </div>
  <div id="custody" class="tabcontent">
    <h3>Revisión</h3>
    <%= render 'custody_check', sample: @custody_order.sample_processed, f: f %>
  </div>
  <div class="form-group">
    <div class="text-center save-worker">
      <%= link_to "Cancelar", classified_services_path, class: "btn btn-primary sical-btn-cancel" %>
      <%= f.submit "Asignar", class: "btn btn-primary", data: {disable_with: 'Please Wait...'}  %>
    </div>
  </div>
  <% end %>

app/views/classified_services/_custody_order_to_check_card.html.erb
<div class="card-group-title">
  <%= title %>
</div>
<div class="card-group-content">
  <div>
    <% if elements.empty?%>
      <div class="form-group">
        <div class="col-md-12 col-form-label card-group-empty-message">
          No tiene mensajes sin leer.
        </div>
      </div>
    <% else %>
      <div class="card-group-elements">
        <% elements.each do |element| %>
          <%= link_to send("work_check_classified_service_path", element), class: "card-group-element-wrapper" do %>
            <div class="card-group-element">
              <div class="col-md-3 text-center subject-date col-form-label">
                <span class="card-group-text is-small is-block">
                  <%= element.created_at.strftime('%I:%M %p') %>
                </span>
                <span class="card-group-text is-small is-block">
                  <%= element.created_at.strftime('%^b %d') %>
                </span>
              </div>
              <div class="col-md-9 col-form-label">
                <span class="card-group-text is-bold is-block">
                  Asunto:
                </span>
                <span class="card-group-text is-small is-block">
                  <%= element.subject %>
                </span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/classified_services/_employees_table.html.erb
<table class="table table-no-bordered table-hover">
  <thead>
    <th>Nombre</th>
    <th>Categoría</th>
    <th>Método</th>
    <th>Acreditado</th>
    <th>Asignación</th>
  </thead>
  <tbody>    
  <% @service.sample_preliminaries.each do |sample_preliminary| %>
      <tr>
        <td><%= sample_preliminary.description %></td>
        <td><%= sample_preliminary.sample_category.name %></td>
        <td><%= sample_preliminary.sample_method_name %></td>
        <td><% if sample_preliminary.sample_method.accredited? %>
            Si
        <% else %> 
            No 
        <% end %></td>
        <td><%= f.collection_select :id, @employees,:id, :name, {}, { name: "selected_employee_#{sample_preliminary.id}", class: "form-control" } %></td>
      </tr>     
  <% end %>   
  </tbody>
</table>  

app/views/classified_services/_filling_up_sample_features.html.erb
<table id="sample-feature" class="table table-hove">
  <thead>
    <tr>
      <th>Nr Muestra</th>
      <% @cols.length.times do |index| %>
        <th><%= @cols[index] %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @sample_processed.amount.times do |index1| %>
      <tr>
        <td><%= @sample_processed.pucp_code + (index1 + 1).to_s %></td>
        <% @cols.length.times do |index2| %>
          <td>
            <div class="form-control">
              <%= @sample_processed.classified_values[index1.to_s+"-"+index2.to_s] %>
            </div>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/classified_services/_form_client.html.erb
<div class="form-group row">
    <label class= "col-md-3 col-form-label">Laboratorio</label>
    <div class="col-md-9">
        <%= service.laboratory.name %>
    </div>
</div>

<div class="form-group row">
    <label class= "col-md-3 col-form-label">Fecha Proxima de Recojo</label>
    <div class="col-md-9">
        <%= service.pick_up_date %>
    </div>
</div>

<div class="form-group row">
    <label class= "col-md-3 col-form-label">Asunto</label>
    <div class="col-md-9">
        <%= service.subject %>
    </div>
</div>

<div class="form-group row">
    <label class= "col-md-3 col-form-label">Muestras</label>
</div>
<div class="col-md-9 offset-md-3">
    <div class="form-group row">
    <div class="col-md-4">Nombre</div>
    <div class="col-md-2">Cantidad</div>
    <div class="col-md-6">Descripcion</div>
    </div>
    <div class="samples-elements">
    <%= render 'show_sample_preliminaries', sample_preliminaries: service.sample_preliminaries %>
    </div>
</div>

app/views/classified_services/_sample_processed_fields.html.erb
<div class="nested-fields">
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Código del Cliente</label>
     <div class="col-md-9">
        <%= f.text_field :client_code, class: "form-control", readonly: true %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Código PUCP</label>
     <div class="col-md-9">
        <%= f.text_field :pucp_code, class: "form-control", readonly: true%>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Categoría</label>
     <div class="col-md-9">
      <%= f.collection_select :sample_category_id, @sample_categories, :id, :name, {}, {class: "form-control", disabled: true} %>
    </div>
  </div>
  <div class="form-group row">
    <label class= "col-md-3 col-form-label">Descripción</label>
     <div class="col-md-9">
        <%= f.text_field :description, class: "form-control", readonly: true %>
    </div>
  </div>
  <!-- <div class="form-group row">
    <label class= "col-md-3 col-form-label">Métodos de Muestra</label>
     <div class="col-md-9">
        <%#= f.collection_select :sample_method_id, @sample_methods, :id, :name, {}, {class: "form-control", disabled: true} %>
    </div>
  </div> -->
  <div class="sample-feature-container col-md-9 offset-md-3">
    <div class="sample-header">
      <span>Más Detalles</span>
    </div>
    <div class="sample-feature-content">
      <div class="row">
        <div class="col-md-9">
          <%= f.label :Descripción %>
        </div>
        <div class="col-md-3">
          <%= f.label :Valor %>
        </div>
      </div>
      <div class="samples-elements">
        <%= f.fields_for :sample_features do |s_f| %>
          <%= render 'sample_feature_fields', f: s_f, disabled: true, editable: false %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/classified_services/_show_sample_preliminaries.html.erb
<div class="form-group row">
    <% sample_preliminaries.each do |sp|%>
      <div class="col-md-4 form-control">
        <%= sp.name%>
      </div>
      <div class="col-md-2  form-control">
        <%= sp.quantity%>
      </div>
        <div class="col-md-5  form-control">
        <%= sp.description%>
      </div>
    <% end %>
</div>

app/views/classified_services/_unclassfied_services_card.html.erb
<div class="card-group-title">
  <%= title %>
</div>
<div class="card-group-content">
  <div>
    <% if elements.empty?%>
      <div class="form-group">
        <div class="col-md-12 col-form-label card-group-empty-message">
          No tiene mensajes sin leer.
        </div>
      </div>
    <% else %>
      <div class="card-group-elements">
        <% elements.each do |element| %>
          <%= link_to send("edit_classified_service_path", element), class: "card-group-element-wrapper" do %>
            <div class="card-group-element">
              <div class="col-md-3 text-center subject-date col-form-label">
                <span class="card-group-text is-small is-block">
                  <%= element.created_at.strftime('%I:%M %p') %>
                </span>
                <span class="card-group-text is-small is-block">
                  <%= element.created_at.strftime('%^b %d') %>
                </span>
              </div>
              <div class="col-md-9 col-form-label">
                <span class="card-group-text is-bold is-block">
                  Asunto:
                </span>
                <span class="card-group-text is-small is-block">
                  <%= element.subject %>
                </span>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/classified_services/_unclassified_services.html.erb
<%= form_for @service, url: classified_service_path, :wrapper => false,  method: :put do |f| %>
  <div id="service" class="tabcontent" style="display: block;">
    <h3>Información</h3>
    <%= render 'show_basic_information', service: @service, f: f %>
  </div>
  <div id="sample" class="tabcontent">
    <h3>Asignación</h3>
    <%= render 'employees_table', employees: @employees, f: f %>
  </div>
  <div class="form-group">
    <div class="text-center save-worker">
      <%= link_to "Cancelar", classified_services_path, class: "btn btn-primary sical-btn-cancel" %>
      <%= f.submit "Asignar", class: "btn btn-primary", data: {disable_with: 'Please Wait...'}  %>
    </div>
  </div>
<% end %>

app/views/classified_services/edit.html.erb
<div class="card">
  <div class="tab">
    <button class="tablinks active" onclick="openSection(event, 'service')">Servicios</button>
    <button class="tablinks" onclick="openSection(event, 'sample')">Asignación de Custodia</button>
  </div>
  <%= render 'unclassified_services' %>
</div>

app/views/classified_services/index.html.erb
<section class="requests-index">
  <div class="card">
    <div class="content">
      <div class="header card-header-text sical-card-header">
        <h1 class="sical-card-title">
          Cadena de Custodia
        </h1>
      </div>
      <div class="sical-content">
        <div class="sub-section-cards">
          <div class="col-md-6 sub-section-card is-unread-card">
            <%= render 'unclassfied_services_card', elements: @services_unclassified, title: "Servicios sin Custodia" %>
          </div>
          <div class="col-md-6 sub-section-card is-read-card">
            <%= render 'custody_order_to_check_card', elements: @custody_order_to_check, title: "Custodia por Revisar" %>
          </div>          
        </div>
      </div>
    </div>
  </div>
</section>

app/views/classified_services/work_check.html.erb
<div class="card">
  <div class="tab">
    <button class="tablinks active" onclick="openSection(event, 'service')">Servicio</button>
    <button class="tablinks" onclick="openSection(event, 'custody')">Custodia</button>
  </div>
  <%= render 'custody_order_to_check' %>
</div>